require("my.options")
require("my.key_mappings")

local bootstrapped = require("my.packer").ensure_installed()
local packer = require("my.plugins")
if bootstrapped then
  vim.cmd("autocmd User PackerComplete echo '[init] Plugins installed, restart nvim' | quitall")
  packer.sync()
else
  require("my.colorscheme")
  require("my.transparent")
  require("my.impatient")
  require("my.alpha")
  require("my.nvim-tree")
  require("my.cmp")
  require("my.lsp")
  require("my.dap")
  require("my.neotest")
  require("my.notify")
  require("my.telescope")
  require("my.treesitter")
  require("my.autopairs")
  require("my.comment")
  require("my.which_key")
  require("my.indentline")
  require("my.dressing")
  require("my.gitsigns")
  require("my.octo")
  require("my.lightbulb")
  require("my.trouble")
  require("my.bufferline")
  require("my.toggleterm")
  require("my.vimwiki")
end
